### ISSUE TITLE
Proper releases

### ISSUE THREAD

**Issue by Gilles86** [VU-Cog-Sci/exptools2#15]
Hey guys,

Great work.

I'm starting a new project and developing an experiment from scratch . Since a year or two I try to do everything properly with with fixed Docker images and conda environments,  but I keep spending a good portion of my precious postdoc time on duck taping backward compatibility issues of different Python packages. I think it would be super helpful if we could make different _releases_ of exptools2 (rather than, e.g., commits) that we can use, so it's super clear with what exptools-code a given experiment was put together.

Github has a nice lemma on this:
https://help.github.com/en/articles/creating-releases

Cheers,
Gilles

**Comment by lukassnoek** [comment]
Yes, I agree. I held off any proper release because it's really still a pre-release. I definitely want @tknapen to look at the Eyetracker code (especially the default eyelink settings) before issuing a proper release. There are also some things to discuss w.r.t. the functionality of the package (i.e., are there still things missing?). Let's have a meeting about this when you guys are back from VSS?

**Comment by Gilles86** [comment]
We both got back this morning, but I feel like a wet paper or something right now. Are you at the Spinoza next week?

I had a quick look at the new code yesterday at the Detroit airport, when rapidly prototyping an experiment. I really liked it. The only problem I had was that I _still_ need 1-1.5 hours to get a working conda environment with exptools2 running. Maybe I am just an idiot, but an idiot with quite some training.
One problem that I overlooked was that the (Sebastiaan Mathot's) `-c cogsci psychopy`-installation package automatically downgrades your Python installation to 2.x, which breaks exptools2.  Maybe we can make a 'recommended' conda-environment for this package? You can upload those to your own anaconda-channel also. Would be neat.

The yaml settings-file is nicely streamlined now, in part by breaking backwards compatibility. The only thing I'm worried about is a use case that I _always_ have. Namely, I need different settings for my laptop and for the stimulus computer. In the old `yaml` [branch](https://github.com/VU-Cog-Sci/exptools/tree/yaml), I implemented an 'overloading'-environment trick to deal with this. This would look something like this:

```
global:
  monitor:
    size: [1024, 768]
  expt:
    n_trials: 100
scanner:
  monitor:
    size: [1920, 1080]
```

Any `exptools` experiment would then always ask which context you are in, before starting a session (where just pressing enter means the `global` environment). Any settings that you do not define for a specific environment (like `scanner`), are pulled out of the `global`-environment.

So whether you want to do this is a big design decision and I can imagine that maybe you and @tknapen  think this is convoluted. However, I do know that this an issue that _always_ comes up and the "no, wait I'll just quickly edit the settings-file for now, next time we'll make it a bit more structured. You are writing this down, right? Wait, I'll open a google doc. Is the scanner running?"-approach is flawed. The separate-branches-for-separate-stimulus-computers is slightly better but very clunky.

Cheers,
Gilles

**Comment by marcoaqil** [comment]
Hey Gilles, just quickly, maybe i can help with the conda environment stuff. I did not encounter big problems installing and using exptools2 with python 3 both on my macbook and on the linux desktop at the 7T (there is an envionrment called Marco_prf or something like that which i have used to run my experiment which you can copy it if needed). I installed exptools2 normally with setup.py -develop, and then psychopy following the conda-relevant instructions on their website.

On the latter part, i also use different settings on macbook and linux. I also thought about different branches first. In the end my simple solution was having different setting files in my experiment repository. and then pick the relevant one when i run the experiment from the command line.

**Comment by Gilles86** [comment]
>Hey Gilles, just quickly, maybe i can help with the conda environment stuff. I did not encounter big problems installing and using exptools2 with python 3 both on my macbook and on the linux desktop at the 7T (there is an envionrment called Marco_prf or something like that which i have used to run my experiment which you can copy it if needed). I installed exptools2 normally with setup.py -develop, and then psychopy following the conda-relevant instructions on their website.

Cool. I got it to work yesterday. It's just that it's always such a headache. Could you do `conda env export > environment.yml`?

> On the latter part, i also use different settings on macbook and linux. I also thought about different branches first. In the end my simple solution was having different setting files in my experiment repository. and then pick the relevant one when i run the experiment from the command line.

So you manually select the settings file and throw it into the run command or something?

**Comment by lukassnoek** [comment]
I have some time next week Wednesday and Thursday in between scans, so we can discuss these things. But to shortly comment on your points:
1. It's reasonable to require Python3 for exptools2, especially since pylink has been ported to Py3.6
2. I had little trouble installing (the latest version of) psychopy (for Py3) on both Linux and Mac. No clue about Py2 though. Regardless, making a conda environment/channel sounds like a good idea.
3. The yaml-settings thing now also works with "overloading", where there is set of default settings (`data/default_settings.yml`), which can be overridden by a custom settings-file. Exptools2 will fall back on the default settings for any setting not defined in your custom settings file. W.r.t. flexibility in different testing environments: I'm doing the same thing as Marco, creating different settings-files for different testing envs, like `settings_lab_uva.yml` and `settings_spinoza_scanner.yml`, and `settings_spinoza_testruimte.yml`, which can be automatically selected based on the hostname, e.g.:

```python
import socket
if socket.gethostname() == 'uva_108':
    settings = 'settings_lab_uva.yml'
else:
    settings = 'settings_spinoza_scanner.yml'
```

I'm also fine with hardcoding some "default" environments in exptools2 in the `data/` directory.

**Comment by Gilles86** [comment]
>I installed exptools2 normally with setup.py -develop, and then psychopy following the conda-relevant instructions on their website.

Great, but they install python 3.5, which makes exptools2 not work, since exptools2 uses this super fancy new python 3.6 string formatting:

```
  File "/Users/gilles/miniconda3/envs/psypy3/lib/python3.5/site-packages/exptools2-0.1.dev0-py3.5.egg/exptools2/core/session.py", line 91
    raise IOError(f"Settings-file {self.settings_file} does not exist!")
```

So what did you do exactly?

**Comment by lukassnoek** [comment]
I used python 3.6 so far, also because the pylink builds are geared towards 3.6. If you guys think we should accommodate all 3.x versions, we should drop the f-strings (fine with me).

**Comment by Gilles86** [comment]
>I used python 3.6 so far, also because the pylink builds are geared towards 3.6. If you guys think we should accommodate all 3.x versions, we should drop the f-strings (fine with me).

I think it's fine to use python 3.6, but it should be easy for users to install your package.

I slightly edited the installation 'script' of [psychopy documentation](http://www.psychopy.org/download.html#anaconda-and-miniconda) to the following:

```
conda create -n psypy3 python=3.6
conda activate psypy3
conda install numpy scipy matplotlib pandas pyopengl pillow lxml openpyxl xlrd configobj pyyaml gevent greenlet msgpack-python psutil pytables requests[security] cffi seaborn wxpython cython pyzmq pyserial
conda install -c conda-forge pyglet pysoundfile python-bidi moviepy pyosf
pip install zmq json-tricks pyparallel sounddevice pygame pysoundcard psychopy_ext psychopy
pip install git+https://github.com/VU-Cog-Sci/exptools2/
```

This does not work. I get a new error:

```
python main.py                                                                               ✔  10641  10:18:41
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
/Users/gilles/miniconda3/envs/psypy3/lib/python3.6/site-packages/exptools2/core/eyetracker.py:19: UserWarning: Pylink is not installed! Eyetracker cannot be used
  warnings.warn(msg)
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    session = FlickerSession('sub-01', settings_file=settings)
  File "main.py", line 42, in __init__
    super().__init__(output_str, output_dir=None, settings_file=settings_file)
  File "/Users/gilles/miniconda3/envs/psypy3/lib/python3.6/site-packages/exptools2/core/session.py", line 72, in __init__
    self.win = self._create_window()
  File "/Users/gilles/miniconda3/envs/psypy3/lib/python3.6/site-packages/exptools2/core/session.py", line 129, in _create_window
    t_per_frame = 1. / self.actual_framerate
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```

**Comment by Gilles86** [comment]
OK so the matplotlib error can be solved by installing qt and pyqt using the following installation pattern:

conda create -n psypy3 python=3.6
conda activate psypy3
conda install numpy scipy matplotlib pandas pyopengl pillow lxml openpyxl xlrd configobj pyyaml gevent greenlet msgpack-python psutil pytables requests[security] cffi seaborn wxpython cython pyzmq pyserial qt pyqt
conda install -c conda-forge pyglet pysoundfile python-bidi moviepy pyosf
pip install zmq json-tricks pyparallel sounddevice pygame pysoundcard psychopy_ext psychopy
pip install git+https://github.com/VU-Cog-Sci/exptools2/

**Comment by Gilles86** [comment]
See https://github.com/VU-Cog-Sci/exptools2/pull/17
