### ISSUE TITLE
Error during isntallation: No module named 'distutils.command.bdist_msi'

### ISSUE THREAD

**Issue by leonsbe** [VU-Cog-Sci/exptools2#26]
Having followed the previous installation steps, after running` pip install git+https://github.com/VU-Cog-Sci/exptools2/` I am getting the following error: 

```
Collecting pocketsphinx
  Downloading pocketsphinx-0.1.15.tar.gz (29.1 MB)
     ---------------------------------------- 29.1/29.1 MB 13.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\leonb\AppData\Local\Temp\pip-install-ruvaa2uk\pocketsphinx_3b3fbb0f2d674c4f8065bf4bb006163c\setup.py", line 20, in <module>
          from distutils.command.bdist_msi import bdist_msi as _bdist_msi
      ModuleNotFoundError: No module named 'distutils.command.bdist_msi'
      [end of output]

```

Any suggestions for troubleshooting?

**Comment by leonsbe** [comment]
I tried installing r-distutils as documented here https://anaconda.org/conda-forge/r-distutils but it looks like it only exists for Linux and OSX.

**Comment by tknapen** [comment]
Hi,Yeah, I haven't seen anyone use exptools2 on windows yet. Nevertheless it may work. Could you send some background information, such as a conda list output?I've also seen similar problems on other systems, from python3.9. Hence the advice in the Readme to use 3.6Cheers Tomas Sent from my iPhoneOn 28 Sep 2022, at 15:43, leonsbe ***@***.***> wrote:﻿
I tried installing r-distutils as documented here https://anaconda.org/conda-forge/r-distutils but it looks like it only exists for Linux and OSX.

**Comment by leonsbe** [comment]
The plan is to work in Linux eventually, I am however running into PsychoPy installation problems on that end so I figured I try it in Windows where I got PsychoPy running. 

The conda list output: ```

# packages in environment at C:\Users\leonb\anaconda3\envs\psychopy2:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
anyio                     3.6.1                    pypi_0    pypi
aom                       3.4.0                h0e60522_1    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arabic_reshaper           2.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
asttokens                 2.0.8                    pypi_0    pypi
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0                   pypi_0    pypi
babel                     2.10.3                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
bleach                    5.0.1                    pypi_0    pypi
blosc                     1.21.1               h74325e0_3    conda-forge
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1004    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.4.26            haa95532_0    anaconda
certifi                   2022.6.15        py39haa95532_0    anaconda
cffi                      1.15.1           py39h0878f49_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
configparser              5.3.0              pyhd8ed1ab_0    conda-forge
coverage                  6.4.4                    pypi_0    pypi
cryptography              37.0.4           py39h7bc7c5c_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1                    pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
dukpy                     0.2.3            py39hb82d6ee_2    conda-forge
entrypoints               0.4                      pypi_0    pypi
esprima-python            4.0.1                   py_2001    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
executing                 1.0.0                    pypi_0    pypi
expat                     2.4.8                h39d44d4_0    conda-forge
fastjsonschema            2.16.1                   pypi_0    pypi
ffmpeg                    5.1.0           gpl_hbb6702b_101    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hce3cb01_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.36.0           py39hb82d6ee_0    conda-forge
freeglut                  3.2.2                h0e60522_1    conda-forge
freetype                  2.12.1               h546665d_0    conda-forge
freetype-py               2.3.0              pyhd8ed1ab_0    conda-forge
future                    0.18.2           py39hcbf5309_5    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
gevent                    21.12.0          py39hb82d6ee_2    conda-forge
ghp-import                2.1.0                    pypi_0    pypi
git                       2.34.1               haa95532_0    anaconda
gitdb                     4.0.9              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.27             pyhd8ed1ab_0    conda-forge
glfw                      3.3.8                h8ffe710_0    conda-forge
glib                      2.72.1               h7755175_0    conda-forge
glib-tools                2.72.1               h7755175_0    conda-forge
greenlet                  1.1.2            py39h415ef7b_2    conda-forge
gst-plugins-base          1.20.3               he07aa86_0    conda-forge
gstreamer                 1.20.3               hdff456e_0    conda-forge
hdf5                      1.12.2          nompi_h2a0e4a3_100    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imageio                   2.21.1             pyhfa7a67d_0    conda-forge
imageio-ffmpeg            0.4.7              pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        4.12.0                   pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
ipykernel                 6.15.2                   pypi_0    pypi
ipython                   8.5.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.7.2                    pypi_0    pypi
jasper                    2.0.33               h77af90b_0    conda-forge
javascripthon             0.11                       py_0    conda-forge
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jpeg                      9e                   h8ffe710_2    conda-forge
json_tricks               3.15.5             pyhd8ed1ab_0    conda-forge
jsonschema                3.2.0                    pypi_0    pypi
jupyter-book              0.13.1                   pypi_0    pypi
jupyter-cache             0.4.3                    pypi_0    pypi
jupyter-client            7.3.5                    pypi_0    pypi
jupyter-core              4.11.1                   pypi_0    pypi
jupyter-server            1.18.1                   pypi_0    pypi
jupyter-server-mathjax    0.2.6                    pypi_0    pypi
jupyter-sphinx            0.3.2                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        1.1.1                    pypi_0    pypi
kiwisolver                1.4.4            py39h2e07f2f_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
latexcodec                2.0.1                    pypi_0    pypi
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libclang                  14.0.6          default_h77d9078_0    conda-forge
libclang13                14.0.6          default_h77d9078_0    conda-forge
libcurl                   7.83.1               h789b8ee_0    conda-forge
libdeflate                1.13                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libflac                   1.3.4                h0e60522_0    conda-forge
libglib                   2.72.1               h3be07f2_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
liblapacke                3.9.0              16_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libopencv                 4.6.0            py39he11e404_0    conda-forge
libopus                   1.3.1                h8ffe710_1    conda-forge
libpng                    1.6.37               h1d00b33_4    conda-forge
libprotobuf               3.20.1               h7755175_1    conda-forge
libsndfile                1.0.31               h0e60522_1    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.39.2               h8ffe710_1    conda-forge
libssh2                   1.10.0               h680486a_3    conda-forge
libtiff                   4.4.0                h92677e6_3    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.14               hf5bbc77_4    conda-forge
libzlib                   1.2.12               h8ffe710_2    conda-forge
linkify-it-py             1.0.3                    pypi_0    pypi
lxml                      4.9.1                    pypi_0    pypi
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
macropy3                  1.1.0b2                    py_0    conda-forge
markdown-it-py            1.1.0                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.3            py39hcbf5309_1    conda-forge
matplotlib-base           3.5.3            py39h581301d_1    conda-forge
matplotlib-inline         0.1.6                    pypi_0    pypi
mdit-py-plugins           0.2.8                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2022.1.0           h6a75c08_874    conda-forge
moviepy                   1.0.3              pyhd8ed1ab_0    conda-forge
msgpack-numpy             0.4.8              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.4            py39h2e07f2f_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
myst-nb                   0.13.2                   pypi_0    pypi
myst-parser               0.15.2                   pypi_0    pypi
nbclient                  0.5.13                   pypi_0    pypi
nbconvert                 6.5.3                    pypi_0    pypi
nbdime                    3.1.1                    pypi_0    pypi
nbformat                  5.4.0                    pypi_0    pypi
nbval                     0.9.6                    pypi_0    pypi
nest-asyncio              1.5.5                    pypi_0    pypi
notebook                  6.4.12                   pypi_0    pypi
numexpr                   2.7.3            py39h2e25243_2    conda-forge
numpy                     1.23.2           py39h1a62c8c_0    conda-forge
opencv                    4.6.0            py39hcbf5309_0    conda-forge
openh264                  2.3.0                h0e60522_0    conda-forge
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1q               h2bbff1b_0
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3            py39h2e25243_0    conda-forge
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathlib2                  2.3.7.post1      py39hcbf5309_1    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.2.0            py39hcef8f5f_2    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0                    pypi_0    pypi
ply                       3.11                       py_1    conda-forge
portaudio                 19.6.0               h0e60522_6    conda-forge
proglog                   0.1.9                      py_0    conda-forge
prometheus-client         0.14.1                   pypi_0    pypi
prompt-toolkit            3.0.31                   pypi_0    pypi
psutil                    5.9.1            py39hb82d6ee_0    conda-forge
psychopy                  2022.1.4         py39hcbf5309_0    conda-forge
psychopy-ext              0.6.0.4                  pypi_0    pypi
psychtoolbox              3.0.18.2                 pypi_0    pypi
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pure-eval                 0.2.2                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
py-opencv                 4.6.0            py39h832f523_0    conda-forge
pybtex                    0.24.0                   pypi_0    pypi
pybtex-docutils           1.0.2                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydata-sphinx-theme       0.8.1                    pypi_0    pypi
pygame                    2.1.2                    pypi_0    pypi
pyglet                    1.4.10                   pypi_0    pypi
pyglfw                    2.5.3            py39hcbf5309_1    conda-forge
pygments                  2.13.0                   pypi_0    pypi
pyo                       1.0.4                    pypi_0    pypi
pyopengl                  3.1.6              pyhd8ed1ab_1    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyosf                     1.0.5                      py_2    conda-forge
pyparallel                0.2.2                    pypi_0    pypi
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pypubsub                  4.0.3                      py_0    conda-forge
pyqmix                    2021.1.2         py39hcbf5309_1    conda-forge
pyqt                      5.15.7           py39hb08f45d_0    conda-forge
pyqt5-sip                 12.11.0          py39h415ef7b_0    conda-forge
pyrsistent                0.18.1                   pypi_0    pypi
pyserial                  3.5                pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39hcbf5309_5    conda-forge
pysoundcard               0.5.2                    pypi_0    pypi
pysoundfile               0.10.3.post1       pyhd3deb0d_0    conda-forge
pytables                  3.7.0            py39hcbeb248_2    conda-forge
pytest                    7.1.3                    pypi_0    pypi
python                    3.9.13          h9a09f29_0_cpython    conda-forge
python-bidi               0.4.2                      py_0    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-gitlab             3.8.1              pyhd8ed1ab_0    conda-forge
python-sounddevice        0.4.1              pyh9f0ad1d_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pywin32                   303              py39hb82d6ee_0    conda-forge
pywinhook                 1.6.2            py39hb82d6ee_4    conda-forge
pywinpty                  2.0.7                    pypi_0    pypi
pyyaml                    6.0              py39hb82d6ee_4    conda-forge
pyzmq                     23.2.1           py39he46f08e_0    conda-forge
qt-main                   5.15.4               h467ea89_2    conda-forge
questplus                 2019.4                     py_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
requests-toolbelt         0.9.1                      py_0    conda-forge
ruamel.yaml               0.17.21          py39hb82d6ee_1    conda-forge
ruamel.yaml.clib          0.2.6            py39hb82d6ee_1    conda-forge
scipy                     1.9.0            py39h316f440_0    conda-forge
send2trash                1.8.0                    pypi_0    pypi
setuptools                65.2.0           py39hcbf5309_0    conda-forge
sip                       6.6.2            py39h415ef7b_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snappy                    1.1.9                h82413e6_1    conda-forge
sniffio                   1.3.0                    pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sphinx                    4.5.0                    pypi_0    pypi
sphinx-book-theme         0.3.3                    pypi_0    pypi
sphinx-comments           0.0.3                    pypi_0    pypi
sphinx-copybutton         0.5.0                    pypi_0    pypi
sphinx-design             0.1.0                    pypi_0    pypi
sphinx-external-toc       0.2.4                    pypi_0    pypi
sphinx-jupyterbook-latex  0.4.6                    pypi_0    pypi
sphinx-multitoc-numbering 0.1.3                    pypi_0    pypi
sphinx-thebe              0.1.2                    pypi_0    pypi
sphinx-togglebutton       0.3.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-bibtex      2.5.0                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlalchemy                1.4.41                   pypi_0    pypi
sqlite                    3.39.2               h8ffe710_1    conda-forge
stack-data                0.5.0                    pypi_0    pypi
svt-av1                   1.2.1                h0e60522_0    conda-forge
tbb                       2021.5.0             h2d74725_1    conda-forge
terminado                 0.15.0                   pypi_0    pypi
tinycss2                  1.1.1                    pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1                    pypi_0    pypi
tornado                   6.2              py39hb82d6ee_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.3.0                    pypi_0    pypi
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
uc-micro-py               1.0.1                    pypi_0    pypi
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py39hb82d6ee_1    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
webassets                 2.0                        py_0    conda-forge
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.3.3              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.1                    pypi_0    pypi
win_inet_pton             1.1.0            py39hcbf5309_4    conda-forge
wxpython                  4.1.1            py39h5cc5705_7    conda-forge
x264                      1!164.3095           h8ffe710_2    conda-forge
x265                      3.5                  h2d74725_3    conda-forge
xarray                    2022.6.0           pyhd8ed1ab_1    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.8.1                    pypi_0    pypi
zmq                       0.0.0                    pypi_0    pypi
zope.event                4.5.0              pyh9f0ad1d_0    conda-forge
zope.interface            5.4.0            py39hb82d6ee_2    conda-forge
zstd                      1.5.2                h7755175_4    conda-forge
```



> Hi,Yeah, I haven't seen anyone use exptools2 on windows yet. Nevertheless it may work. Could you send some background information, such as a conda list output?I've also seen similar problems on other systems, from python3.9. Hence the advice in the Readme to use 3.6Cheers Tomas Sent from my iPhoneOn 28 Sep 2022, at 15:43, leonsbe ***@***.***> wrote:﻿ I tried installing r-distutils as documented here https://anaconda.org/conda-forge/r-distutils but it looks like it only exists for Linux and OSX. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
